server:
  port: 2013

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smoker?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    hostName: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 10000

  envo: default
  profiles:
    #选择环境
    active: default

  servlet:
    multipart:
      # 上传文件总的最大值
      max-request-size: 10MB
      # 单个文件的最大值
      max-file-size: 10MB

  ## jsp
  mvc:
    view:
#      prefix: /WEB-INF/
      suffix: .html

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.island.monster.bean

island:
  ## 访问路径（虚拟路径）
  location:
    painting: /image/painting/
    music-image: /image/music_image/
    movie-image: /image/movie_image/
    landscape-image: /image/landscape-image/
    background-image: /image/background-image/
    post-image: /image/post-image/
    joke-image: /image/joke-image/
    music: /sound/music/
  ## 保存路径（真实路径）
  path:
    log-path: F:/timeIsland/logs
    painting-path: E:\island\images\painting\
    music-image-path: E:\island\images\musicImage\
    movie-image-path: E:\island\images\movieImage\
    background-image-path: E:\island\images\backgroundImage\
    landscape-image-path: E:\island\images\landscapeImage\
    post-image-path: E:\island\images\postImage\
    joke-image-path: E:\island\images\jokeImage\
    music-path: E:\island\sound\music\


---
#线上环境
server:
  port: 2013

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smoker?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    hostName: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 10000

  envo: dev
  profiles: dev

island:
  ## 访问路径（虚拟路径）
  location:
    painting: /image/painting/
    music-image: /image/music_image/
    movie-image: /image/movie_image/
    landscape-image: /image/landscape-image/
    background-image: /image/background-image/
    music: /sound/music/
    post-image: /image/post-image/
  ## 保存路径（真实路径）
  path:
    log-path: F:/timeIsland/logs
    painting-path: E:\island\images\painting\
    music-image-path: E:\island\images\musicImage\
    movie-image-path: E:\island\images\movieImage\
    background-image-path: E:\island\images\backgroundImage\
    landscape-image-path: E:\island\images\landscapeImage\
    music-path: E:\island\sound\music\

